#!/usr/bin/env bash

set -euo pipefail

python -m venv --copies --clear --upgrade-deps ".venv"
source scripts/activate
python -m pip install --upgrade pip setuptools wheel
python -m pip install --editable ".[dev,cli,testing]"
