#!/usr/bin/env bash

set -euo pipefail

source scripts/activate
pytest -vv -ra --strict-markers --strict-config --durations 10 --new-first --basetemp .test_artifacts --asyncio-mode auto tests/performance
