on:
  push:
    branches:
      - main
    paths:
      - version

permissions:
  id-token: write
  contents: read

jobs:
  release:
    runs-on: ${{ matrix.packages.os }}

    strategy:
      fail-fast: false

      matrix:
        packages:
          - {os: "ubuntu-latest", python-version: "3.12", package: "python-sdist"}
          - {os: "ubuntu-latest", python-version: "3.12", package: "python-wheel"}

    steps:
      - uses: actions/checkout@v4
      - run: ./bin/setup
      - run: ./bin/package-${{ matrix.packages.package }}
      - run: ./bin/publish-${{ matrix.packages.package }}
