name: test
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

  push:
    branches:
      - main

  schedule:
    - cron: '0 8 * * 1-5' # At 08:00 on every day-of-week from Monday through Friday.

  workflow_dispatch:

defaults:
  run:
    shell: bash -ieo pipefail {0}

jobs:
  test:
    name: ${{ matrix.test-type }} ${{ matrix.os }} python${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"
        python-version:
          - "3.12"
        test-type:
          - "acceptance"
          - "functional"
          - "performance"
          - "property"
          - "security"
          - "smoke"
          - "unit"

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: install python${{ matrix.python-version }}
        id: install-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: setup
        run: bin/setup

      - name: run tests
        run: bin/test-${{ matrix.test-type }}
