on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

  push:
    branches:
      - main

  schedule:
    - cron: '0 8 * * *' # At 08:00 UTC every day.

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"
        python-version:
          - "3.12"
        test-type:
          - "acceptance"
          - "functional"
          - "performance"
          - "property"
          - "security"
          - "smoke"
          - "unit"

    steps:
      - uses: actions/checkout@v4
      - run: ./bin/setup
      - run: ./bin/test-${{ matrix.test-type }}
