on:
  pull_request:

  schedule:
    - cron: '0 8 * * *' # At 08:00 UTC every day.

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"
        python-version:
          - "3.12"
        test-type:
          - "acceptance"
          - "functional"
          - "package-python-sdist"
          - "package-python-wheel"
          - "smoke"

    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@master
      - run: ./bin/setup
      - run: ./bin/test-${{ matrix.test-type }}
